### ISSUE TITLE
Bug in calculating set O

### ISSUE THREAD

**Issue by adthoms** [anchalsinha/GridworldSimulator#2]
At this [line](https://github.com/anchalsinha/GridworldSimulator/blob/7783acf887efb020bf1c4bd8e949048e7293da85/gridworld/configuration.py#L26), we are not calculating observations correctly. The code should read something like:

randNum <-- generate random number on open interval [0,1]

if (randNum < 1 - (np.ceil(h) - h))
  o = np.ceil(h)
else
  o = np.floor(h)

**Comment by anchalsinha** [comment]
@adthoms We are treating the set O as a 'lookup table', similar to P. For each state, it will store both outputs and probabilities to be randomly selected later. You are right though, we are currently not randomly choosing an output, but instead just returning both outputs with probabilities in this line [here](https://github.com/anchalsinha/GridworldSimulator/blob/7783acf887efb020bf1c4bd8e949048e7293da85/gridworld/simulator.py#L38). 

I'll replace this line with the selection of an output using the probabilities and submit a PR.

**Comment by adthoms** [comment]
@anchalsinha nice, I'll update the sudo code to reflect this design decision.
